origin_url: https://rapla.dhbw-karlsruhe.de/rapla?page=ical&user=freudenmann&file=TINF23B1
blocklist:
    - .Grundlagen der KI (KI & BV)
    - STUV-ADA 3 (freiwilliger Zusatz)
    - e Business
    - Mobile Applikationen
    - Nachklausuren  (120 min)
    - Ethik für Informatiker (WM-A)
    - Exkursion Fa. VECTOR in Karlsruhe
    - Netzwerktreffen für Studentinnen
    - Computergraphik  (BV & CG)
    - Klausurwoche 5. Semester
    - Klausurwoche
    - Klausur eBusiness  (90 min)
    - Klausur Wahlmodul Künstliche Intelligenz und Bildverarbeitung  (120 min)
    - Klausur Wahlmodul Computergrafik und Bildverarbeitung  (120 min)
    - Klausur Web-Services (60 min)
    - Klausur Zuverlässige Embedded Systeme (60 min)
    - Klausur Forensik (60 min)
    - Klausur Mathematische Grundlagen der Kryptographie (60 min)
    - Faschingsdienstag
    - Karfreitag
    - Ostermontag
    - Pfingstmontag
    - Fronleichnam
    - angewandtes Projektmanagement
    - Interaktive Systeme (KI & IS)
    - Bildverarbeitung (KI & BV)
    - Digitale Forensik  (WMA)
    - Gamification
    - Web-Services (WM-A)
    - Evolutionäre Algorithmen
    - Hl. 3 Könige
    - Klausurwoche 5. Semester
    - Kolloquium 2025  ( min)
    - Kolloquium 2025 Vorbereitung  ( min)
    - Beginn Theorie 5. Semester
    - Studienbeginn 5. Semester
    - Tag der deutschen Einheit
    - Karfreitag
    - Ostermontag
    - Studienarbeit
    - Bildverarbetiung (BV & CG)
    - Mathematische Grundlagen der Kryptographie
    - Grundlagen der KI (KI & IS)
    - mündl. Prüfung ( min)
    - Exkursionstermin TINF23 5. Semester