origin_url: "https://rapla.dhbw-karlsruhe.de/rapla?page=ical&user=freudenmann&file=TINF23B1"
blocklist:
  - Beginn Theorie 5. Semester
  - Studienbeginn 5. Semester
  - Tag der deutschen Einheit
  - Hl. 3 Könige
  - Klausurwoche 5. Semester
  - Studienarbeit
  - Allerheiligen
  - Netzwerktreffen für Studentinnen
  - Nachklausuren  (120 min)
  - STUV-ADA 3 (freiwilliger Zusatz)
  - angewandtes Projektmanagement
  - Interaktive Systeme (KI & IS)
  - Ethik für Informatiker (WM-A)
  - Digitale Forensik  (WMA)
  - Web-Services (WM-A)
  - Mathematische Grundlagen der Kryptographie
  - Evolutionäre Algorithmen
  - Entwurf mobiler Applikationen
  - Klausur Forensik (60 min)
  - e Business
  - Consulting und techn. Vertrieb
  - Klausur Zuverlässige Embedded Systeme (60 min)
  - Exkursion Fa. VECTOR in Karlsruhe
  - Klausur eBusiness  (90 min)
  - Ethik für Informatiker (WM-A)
  - Klausur Mathematische Grundlagen der Kryptographie (60 min)
  - .Grundlagen der KI